name: finances
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+10

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  currency_text_input_formatter: ^2.2.3
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  graphic: ^2.3.0
  intl: any
  material_symbols_icons: ^4.2762.0
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.3.3+1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
